# Generated by Django 4.0.5 on 2022-06-13 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text="Customer's website domain name.", max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(help_text='Stripe ID of customer', max_length=255, unique=True, verbose_name='Stripe Customer ID')),
                ('cloudflare_zone_id', models.CharField(help_text='CF Zone ID of customer', max_length=255, unique=True, verbose_name='Cloudflare Zone ID')),
                ('digitalocean_droplet_id', models.CharField(help_text='DO Droplet ID of customer', max_length=255, unique=True, verbose_name='DigitalOcean Droplet ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
