# Generated by Django 4.0.5 on 2022-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_client_options_serverupgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverupgrade',
            options={'verbose_name': 'Server Upgrade Request', 'verbose_name_plural': 'Server Upgrade Requests'},
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='Web Mastered Ltd.', help_text="Customer's company name.", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
