# Generated by Django 4.0.6 on 2022-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_serverupgrade_options_client_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cloudflare_zone_id',
            field=models.CharField(help_text='CF Zone ID of customer', max_length=255, verbose_name='Cloudflare Zone ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(help_text="Customer's company name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='digitalocean_droplet_id',
            field=models.CharField(help_text='DO Droplet ID of customer', max_length=255, verbose_name='DigitalOcean Droplet ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='domain_name',
            field=models.CharField(help_text="Customer's website domain name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(help_text='Stripe ID of customer', max_length=255, verbose_name='Stripe Customer ID'),
        ),
    ]
