# Generated by Django 4.0.5 on 2022-06-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('external_page_slug', models.CharField(help_text='Enter the slug of the external page.', max_length=255, verbose_name='External page slug')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
