# Generated by Django 4.0.5 on 2022-06-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_externalpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalpage',
            options={'verbose_name': 'Enternal Page', 'verbose_name_plural': 'External Pages'},
        ),
    ]
