# Generated by Django 4.0.5 on 2022-06-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalpage',
            options={'verbose_name': 'External Page', 'verbose_name_plural': 'External Pages'},
        ),
    ]
