# Generated by Django 4.0.6 on 2022-07-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('flex', '0019_alter_flexpage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWebsite',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('external_page_url', models.CharField(help_text='Enter the URL of the external page.', max_length=255, verbose_name='External page URL')),
            ],
            options={
                'verbose_name': 'External Website',
                'verbose_name_plural': 'External Websites',
            },
            bases=('wagtailcore.page',),
        ),
    ]
