# Generated by Django 4.0.5 on 2022-06-09 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailimages', '0024_index_image_file_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text="Create new staff roles here, these roles an be assigned to 'staff' users.", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_text', wagtail.fields.RichTextField(blank=True, help_text='This text will be displayed below the logo in the footer.', null=True, verbose_name='Footer text')),
                ('cookie_policy_page', models.ForeignKey(blank=True, help_text='Set your cookie policy page, this page will be listed in specific parts of the menus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Cookie policy')),
                ('darkmode_logo', models.ForeignKey(blank=True, help_text="Choose an image for this site's dark mode logo. This logo will be displayed on dark backgrounds.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('lightmode_logo', models.ForeignKey(blank=True, help_text="Choose an image for this site's light mode logo. This logo will be displayed on light backgrounds.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('privacy_policy_page', models.ForeignKey(blank=True, help_text='Set your privacy policy page, this page will be listed in specific parts of the menus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Privacy policy')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('site_icon', models.ForeignKey(blank=True, help_text='Site icons are what you see in browser tabs and bookmark bars, please upload a square image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('terms_and_conditions_page', models.ForeignKey(blank=True, help_text='Set your terms & conditions page, this page will be listed in specific parts of the menus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Terms & conditions')),
            ],
            options={
                'verbose_name': 'Website Settings',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ManyToManyField(blank=True, help_text='You can select multiple roles by doing CMD+Click or CTRL+Click', to='dashboard.staffroles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
