# Generated by Django 4.0.5 on 2022-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Enter the email address for this business', max_length=254, null=True),
        ),
    ]
