# Generated by Django 4.0.5 on 2022-06-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('dashboard', '0002_websitesettings_business_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalMenuMainSectionPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', models.ForeignKey(blank=True, help_text='Set a page to display in the main section of the modal menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modalmenu_mainsect_page', to='wagtailcore.page', verbose_name='Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
