# Generated by Django 4.0.5 on 2022-06-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('dashboard', '0003_modalmenumainsectionpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalmenumainsectionpages',
            name='mainsect_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modalmenu_mainsect_page', to='dashboard.websitesettings'),
        ),
        migrations.AlterField(
            model_name='modalmenumainsectionpages',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Set a page to display in the main section of the modal menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page'),
        ),
    ]
