# Generated by Django 4.0.5 on 2022-06-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_modalmenusubsectionpages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffRoles',
        ),
    ]
