# Generated by Django 4.0.5 on 2022-06-12 21:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_delete_staff_delete_staffroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('account_platform', models.CharField(choices=[('Instagram', 'fa-brands fa-instagram'), ('LinkedIn', 'fa-brands fa-linkedin'), ('Facebook', 'fa-facebook'), ('Github', 'fa-github')], help_text='Select the social media platform for this account.', max_length=255, verbose_name='Platform')),
                ('account_username', models.CharField(help_text='Enter the username for your account with this social media platform.', max_length=100, verbose_name='Username')),
                ('account_url', models.URLField(help_text='Enter the URL to your account for this social media platform.', max_length=1024, verbose_name='Account URL')),
                ('account', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_account', to='dashboard.websitesettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
