# Generated by Django 4.0.5 on 2022-06-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_socialnetworkaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkaccounts',
            name='account_platform',
            field=models.CharField(choices=[('fa-instagram', 'Instagram'), ('fa-linkedin', 'LinkedIn'), ('fa-facebook', 'Facebook'), ('fa-github', 'GitHub')], help_text='Select the social media platform for this account.', max_length=255, verbose_name='Platform'),
        ),
    ]
