# Generated by Django 4.0.5 on 2022-06-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_socialnetworkaccount_socialmediaaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='company_description',
            field=models.CharField(blank=True, help_text='Enter the description for this company', max_length=2000),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='company_legal_name',
            field=models.CharField(blank=True, help_text='Enter the legal name of the company', max_length=255, verbose_name='Legal Business Name'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='company_name',
            field=models.CharField(blank=True, help_text='Enter the name of the company', max_length=255),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='company_slogan',
            field=models.CharField(blank=True, help_text='Enter the company slogan', max_length=1000),
        ),
    ]
