# Generated by Django 4.0.5 on 2022-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_contact_gdpr_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gdpr_consent',
            field=models.BooleanField(default=False),
        ),
    ]
