# Generated by Django 4.0.5 on 2022-06-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_contact_gdpr_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='gdpr_consent',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='marketing_consent',
        ),
    ]
