# Generated by Django 4.0.5 on 2022-06-30 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_remove_contact_gdpr_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
